@startuml
title Процесс открытия депозита (As Is, верхний уровень)

|Отдел кредитования|
start
:Ежедневно рассчитывает базовые ставки в Excel;
:Передаёт Excel-файл в бэк-офис по почте;

|Клиент|
:Хочет открыть депозит;

if (Был звонок в кол-центр?) then (Да)
  |Кол-центр|
  :Регистрирует обращение;
  :Передаёт его в АБС;

  |Бэк-офис|
  :Заранее обрабатывает заявку в АБС;
  :Определяет ставку;
  :При необходимости согласует\nспециальную ставку с кредитованием;
  :Сохраняет ставку в АБС;

  |АБС|
  :Отправляет клиенту SMS;
endif

|Клиент|
:Приходит в отделение;

|Фронт-офис / отделение|
:Принимает заявку;

if (Ставка уже есть в АБС?) then (Да)
  :Берёт ставку из АБС;
else (Нет)
  :Запрашивает ставку в бэк-офисе;

  |Бэк-офис|
  :Определяет ставку;
  :При необходимости согласует\nспециальную ставку с кредитованием;
  :Возвращает ставку во фронт-офис;

  |Фронт-офис / отделение|
  :Получает ставку;
endif

:Озвучивает ставку клиенту;

|Клиент|
:Подтверждает открытие депозита;

|Фронт-офис / отделение|
:Создаёт депозит в АБС;
:Выдаёт документы;
:После подписания загружает документы в АБС;

stop
@enduml